-- Productos ecológicos y sostenibles
INSERT INTO producto (
  nombre_prod,
  origen_prod,
  material_principal,
  categoria,
  vida_util_meses,
  precio,
  reutilizable,
  cantidad
)
VALUES
  ('Bolsa de Tela Reforzada',             'Chile', 'Algodón',            'Bolsas',         12, 2500, TRUE,  10),
  ('Set de Cubiertos de Bambú (3 uds.)',   'China', 'Bambú',              'Utensilios',     12, 3200, TRUE,  15),
  ('Pajillas de Acero Inoxidable (5 uds.)','USA',   'Acero Inoxidable',    'Utensilios',     12, 4500, TRUE,  20),
  ('Platos Compostables (10 uds.)',        'China', 'Bagazo de Caña',     'Utensilios',      1, 1800, FALSE, 30),
  ('Vasos Cartón Compostable (10 uds.)',   'Chile', 'Cartón',             'Vasos',           1, 2000, FALSE, 25),
  ('Envoltura Cera de Abeja (2 uds.)',     'Chile', 'Algodón/Cera',       'Almacenamiento',  6, 3500, TRUE,  12),
  ('Bolsas Biodegradables (10 uds.)',      'China', 'PLA',                'Bolsas',         1, 1700, FALSE, 30),
  ('Cepillo de Dientes de Bambú',          'USA',   'Bambú',              'Higiene',         6, 2500, TRUE,  40),
  ('Pajillas de Vidrio (3 uds.)',          'China', 'Vidrio',             'Utensilios',     12, 5000, TRUE,  18),
  ('Servilletas de Tela (4 uds.)',         'Chile', 'Algodón',            'Hogar',          12, 3000, TRUE,  22),
  ('Paño Microfibra Reutilizable',         'Chile', 'Microfibra',         'Hogar',           6, 1800, TRUE,  30),
  ('Cucharas Compostables (10 uds.)',      'China', 'Bagazo de Caña',     'Utensilios',      1, 1500, FALSE, 35),
  ('Botella Deportiva Tritán 500 ml',      'China', 'Tritán',             'Bebidas',        12, 5500, TRUE,  16),
  ('Tazón de Bagazo de Caña 400 ml',       'China', 'Bagazo de Caña',     'Vasos',           1, 2200, FALSE, 28),
  ('Lunchera Acero Inoxidable 500 ml',     'Chile', 'Acero Inoxidable',    'Almacenamiento', 12, 6000, TRUE,  14),
  ('Cinta Adhesiva Papel Kraft',           'USA',   'Papel',              'Hogar',           1, 1200, FALSE, 50),
  ('Jabón Sólido Ecológico',               'Chile', 'Manteca de Karité',  'Higiene',         3, 2000, FALSE, 60),
  ('Filtro de Café de Tela',               'China', 'Algodón',            'Hogar',           6, 1800, TRUE,  20),
  ('Caja Almuerzo Bambú 600 ml',           'China', 'Bambú',              'Almacenamiento', 12, 4800, TRUE,  12),
  ('Popotes de Papel (50 uds.)',           'Chile', 'Papel',              'Utensilios',      1, 1000, FALSE, 40),
  ('Bolsa de Raffia Reutilizable',         'Chile', 'Raffia',             'Bolsas',         12, 2600, TRUE,  18),
  ('Pinzas de Madera para Ropa (10 uds.)', 'China', 'Madera',             'Hogar',          12, 1400, TRUE,  25),
  ('Toalla de Bambú',                      'USA',   'Bambú',              'Higiene',        12, 3500, TRUE,  30),
  ('Pañuelo Multifunción de Tela',         'China', 'Algodón',            'Higiene',         6, 1800, TRUE,  20),
  ('Jabonera de Madera',                   'Chile', 'Madera',             'Hogar',          12, 2000, TRUE,  15);
